name: Publishing

permissions:
  packages: write
  contents: write

on:
  push:
    tags:
      - '*.*'
      

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release /p:Version=${{github.ref_name}} /p:AssemblyVersion=${{github.ref_name}}
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release --filter TestCategory!=RequiresHardware
    - name: Pack
      run: dotnet pack --configuration Release  /p:Version=${{github.ref_name}} /p:AssemblyVersion=${{github.ref_name}}
    - name: Push to NuGet
      run: dotnet nuget push TrulyRandom/bin/Release/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
    - name: Push to Github Packages
      run: dotnet nuget push TrulyRandom/bin/Release/*.nupkg --api-key ${{secrets.GITHUB_TOKEN}} --source https://nuget.pkg.github.com/RomashkinAndrew/index.json --skip-duplicate
    - name: Create release
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/* --quiet
        comment=$(git tag -l --format='%(contents)' ${{github.ref_name}})
        cd TrulyRandom/bin/Release/
        zip "TrulyRandom ${{github.ref_name}}.zip" * -r
        gh release create "${{github.ref_name}}" "TrulyRandom ${{github.ref_name}}.zip" --repo="$GITHUB_REPOSITORY"  --title="TrulyRandom v${{github.ref_name}}" -n "$comment"