name: Unit tests

on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup
    - uses: actions/checkout@v4
      uses: actions/setup-dotnet@v4
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release --filter TestCategory!=RequiresHardware
